### ISSUE TITLE
Reproduce Eulenberg 2017

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#446]
# Goal

Reproduce the t-SNE of https://www.nature.com/articles/s41467-017-00623-3
![image](https://user-images.githubusercontent.com/21954664/214584982-14e22e56-cd20-4af9-a1c8-30da5a57ec95.png) with PyTorch/Jax + ehrapy (for UMAP etc) + cellrank with pseudotime kernel

# Approach

1. Obtain the datasets from https://www.kaggle.com/c/diabetic-retinopathy-detection/data
2. Read the Method section of the paper closely
3. Try to get the mxnet to run (https://github.com/theislab/deepflow -> run.py)
4. Reimplement the mxnet with PyTorch or Jax
5. Get the embedding into an AnnData object (obsm) or something -> PCA -> UMAP
6. Throw it into cellrank -> try to reproduce the figure

**Comment by Zethson** [comment]
```
Running into issues with Creating .rec file from /home/zeth/PycharmProjects/deepflow_reproduction/deepflow/records/test_fold_1.lst in /home/zeth/PycharmProjects/deepflow_reproduction/deepflow/records
multiprocessing not available, fall back to single threaded encoding
imread read blank (None) image for file: /home/zeth/PycharmProjects/deepflow_reproduction/deepflow/records/../data/CellCycle/Anaphase/30890_merged.jpg
Traceback (most recent call last):
  File "im2rec.py", line 302, in <module>
    record.write_idx(item[0], s)
  File "/home/zeth/miniconda3/envs/deepflow/lib/python3.5/site-packages/mxnet/recordio.py", line 268, in write_idx
    self.write(buf)
  File "/home/zeth/miniconda3/envs/deepflow/lib/python3.5/site-packages/mxnet/recordio.py", line 118, in write
    ctypes.c_size_t(len(buf))))
TypeError: object of type 'NoneType' has no len()
Creating .rec file from /home/zeth/PycharmProjects/deepflow_reproduction/deepflow/records/train_fold_1.lst in /home/zeth/PycharmProjects/deepflow_reproduction/deepflow/records
multiprocessing not available, fall back to single threaded encoding
imread read blank (None) image for file: /home/zeth/PycharmProjects/deepflow_reproduction/deepflow/records/../data/CellCycle/S/15619_merged.jpg
Traceback (most recent call last):
  File "im2rec.py", line 302, in <module>
    record.write_idx(item[0], s)
  File "/home/zeth/miniconda3/envs/deepflow/lib/python3.5/site-packages/mxnet/recordio.py", line 268, in write_idx
    self.write(buf)
  File "/home/zeth/miniconda3/envs/deepflow/lib/python3.5/site-packages/mxnet/recordio.py", line 118, in write
    ctypes.c_size_t(len(buf))))
TypeError: object of type 'NoneType' has no len()
```

**Comment by Zethson** [comment]
See ehrapy-reproducibility
